import type { Metadata } from "next";
import { Inter , Kanit  } from "next/font/google";
import "./globals.css";
import "@fontsource/kanit";

const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({ weight: ['400'], subsets: ["latin"] });


export const metadata: Metadata = {
  title: "restaurant-finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${inter.className} ${kanit.className}`}>{children}</body>
    </html>
  );
}
